Newfeatures
david63011/Pro-website pull request #3
Opened 2022-08-19 16:41 UTC by david63011

2022-08-19 17:48 UTC, Qoosim requested changes
Hi @david63011 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ]  has linter error.

![linter-error](https://user-images.githubusercontent.com/26597432/185677677-72dcbd31-9b1d-41a9-bb7a-572ee917e34e.png)

- [ ] Kindly fix the error and submit for another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-19 18:09 UTC, david63011 commented
hey qoosim,
that was for javascript and I don't have any javascript thats why it
failed. it is only css and html I cant change anything


On Fri, Aug 19, 2022 at 1:48 PM Qoosim AbdulGhaniyy <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @david63011 <https://github.com/david63011> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that
>
>    - has linter error.
>
> [image: linter-error]
> <https://user-images.githubusercontent.com/26597432/185677677-72dcbd31-9b1d-41a9-bb7a-572ee917e34e.png>
>
>    - Kindly fix the error and submit for another review
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/david63011/Pro-website/pull/3#pullrequestreview-1079178485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYBOZP53E74DVO5HNELWONTVZ7CHNANCNFSM57BKIUIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-19 18:10 UTC, david63011 commented
there wasnt an error I can change

On Fri, Aug 19, 2022 at 2:09 PM David underwood ***@***.***> wrote:

> hey qoosim,
> that was for javascript and I don't have any javascript thats why it
> failed. it is only css and html I cant change anything
>
>
> On Fri, Aug 19, 2022 at 1:48 PM Qoosim AbdulGhaniyy <
> ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @david63011 <https://github.com/david63011> ,
>>
>> While you made a great effort in this project, unfortunately, I cannot
>> proceed to review your code.
>> Invalid Code Review Request
>>
>> You have submitted a project, that
>>
>>    - has linter error.
>>
>> [image: linter-error]
>> <https://user-images.githubusercontent.com/26597432/185677677-72dcbd31-9b1d-41a9-bb7a-572ee917e34e.png>
>>
>>    - Kindly fix the error and submit for another review
>>
>> Your Code Review Request will be marked as invalid in your Dashboard, so
>> please submit a new one once you are ready 🙏
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *Invalid Code Review Request does not count into the code reviews limit.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/david63011/Pro-website/pull/3#pullrequestreview-1079178485>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AYBOZP53E74DVO5HNELWONTVZ7CHNANCNFSM57BKIUIA>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-08-19 19:38 UTC, vickymarz requested changes
Hi @david63011, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

This activity requires you to configure linters for HTML&CSS excluding javascript. Kindly remove the eslint workflow from your linters.yml file 👍🏼 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-19 20:17 UTC, ichala requested changes
Hi @david63011,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

### ❌ Invalid Code Review Request
You have submitted a project that has no linters, Kindly make sure your linters are all working before submitting the PR.

**_kindly follow this [guide ](https://github.com/microverseinc/linters-config/tree/master/html-css)on how to install HTML/CSS Linters 👍🏼_**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Invalid Code Review Request does not count into the code reviews limit.**

2022-08-19 22:08 UTC, mwanawabangona requested changes
Hi @david63011,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-19 22:08 UTC, mwanawabangona commented on index2.html
> +        </div>
- [ ] `required`
- [ ] its not best practice to break one word into chuncks according to to the [html&Css](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) sematic tags kindly put the pagragraph in a ptag

2022-08-19 22:08 UTC, mwanawabangona commented on index2.html
> +            <div class="html">HTML</div>
- [ ] `required`
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (a tag).
- Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using href.
- [ ] to the [html&Css](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) sematic tags

it should like something like this 
![image](https://user-images.githubusercontent.com/66230306/185713238-e06ed602-1aeb-4dff-87ea-f809a08d35e0.png)

2022-08-20 01:04 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @david63011  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Highlights
- Add a descriptive description in your pull request :heavy_check_mark:👨🏻‍💻
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- check comment under the review
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 01:26 UTC, merged